routes/web.php
<?php


/**
 * Home page
 */
Route::get('/', 'HomeController@index');
Route::get('/create_topic', 'HomeController@createTopic')->name('home.create_topic');
Route::post('/create_topic', 'HomeController@storeTopic')->name('home.store_topic');


/**
 * Admin Dashboard
 */
Route::get('/admin', 'Admin\DashboardController@index')->name('admin.dashboard'); 
Route::group([
  'prefix' => 'admin', 
  'namespace' => 'Admin',
  'as' => 'admin.'
], function(){
  
  Route::resource('forums', 'ForumsController',[
    'except' => ['show']
  ]);

  Route::get('categories/pdf', 'CategoriesController@pdf')->name('categories.pdf');
  Route::resource('categories', 'CategoriesController',[
    'except' => ['show']
  ]);
});

/**
 * Forum pages
 */
Route::resource('forums', 'ForumsController',[
  'only' => 'show'
]);
Route::resource('forums.categories', 'CategoriesController', [
  'only' => 'show'
]);


/**
 * Topic And Comment Pages
 */
Route::resource('forums.categories.topics', 'TopicsController',[
  'only' => ['create', 'store']
]);
Route::resource('topics', 'TopicsController', [
  'only' => ['show', 'edit', 'update']
]);
Route::post('/topics/{slug}/postStar', 'TopicsController@postStar')->name('topics.star');
Route::resource('topics.comments', 'CommentsController',[
  'except' => ['index', 'show', 'destroy']
]);



/**
 * Profile pages
 */
Auth::routes();
Route::get('/profile/password', 'ProfileController@editPassword')->name('profile.edit_password');
Route::post('/profile/password', 'ProfileController@updatePassword')->name('profile.update_password');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::patch('/profile/update', 'ProfileController@update')->name('profile.update');

/**
 * Message pages
 */

Route::get('/profile/message', 'MessageController@index')->name('profile.message.index');
Route::resource('profile.message', 'MessageController', [
  'except' => ['index','edit','destroy']
]);
Route::get('/profile/{id}', 'ProfileController@show')->name('profile.show');

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use willvincent\Rateable\Rateable;

class Topic extends Model
{
    use Sluggable, SluggableScopeHelpers, Rateable;

    protected $fillable = ['title', 'body', 'views', 'category_id', 'user_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }    

}

app/Http/Controllers/TopicsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Topic;
use Auth;
use willvincent\Rateable\Rating;

class TopicsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => 'show']);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($forumId, $categoryId)
    { 
        return view('topics.create', compact('forumId', 'categoryId'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $forumId, $categoryId)
    {
        $this->validate($request, [
          'title' => 'required|max:50',
          'body' => 'required|max:10000',
          'g-recaptcha-response' => 'required'
        ]);

        $topic = new Topic;
        $topic->title = $request->title;
        $topic->body = $request->body;
        $topic->user_id = Auth::user()->id;
        $topic->category_id = $categoryId;
        $topic->views = 1;
        $topic->save();

        return redirect()->route('topics.show', $topic->slug);


    }

/* resource nested di pisah supaya url show topic nya lebih bersih */

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $topic = Topic::findBySlug($slug);
        $topic->views += 1;
        $topic->save();
        $comments = Topic::findBySlug($slug)->comments()->paginate(20);
        return view('topics.show', compact('topic', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $topic = Topic::findBySlug($slug);
        if ($topic->user->id == Auth::id()) {
          return view('topics.edit', compact('topic'));
        }

        return redirect()->back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $slug)
    {
        $topic = Topic::findBySlug($slug);
        if (!$topic->user->id == Auth::id()) {
          return redirect()->back();
        }

        $this->validate($request, [
          'title' => 'required|max:50',
          'body' => 'required|max:10000',
        ]);

        $topic->update($request->all());

        return redirect()->route('topics.show', $topic->slug);
    }


    public function postStar(Request $request, $slug)
    {
        $topic = Topic::findBySlug($slug);
        $validate =  $topic->ratings()->where('user_id', \Auth::id())->first();

        if (count($validate)) {
          return 'Memberi rating hanya bisa di lakukan sekali';      
        } else {
          $rating = new Rating;
          $rating->rating = $request->rating;
          $rating->user_id = \Auth::id();
          $topic->ratings()->save($rating);

          return 'Thanks for rating';
        }

    }

}

resources/views/topics/create.blade.php
@extends('layouts.app')

@section('style')

@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
          
            <div class="panel panel-default">
                <div class="panel-heading">Create new topic</div>

                <div class="panel-body">
                    {!! Form::open(['route' => ['forums.categories.topics.store', $forumId, $categoryId]])!!}
                          <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                              {!! Form::label('title', 'Title') !!}
                              {!! Form::text('title', null, ['class' => 'form-control']) !!}
                              <small class="text-danger">{{ $errors->first('title') }}</small>
                          </div>  

                          <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                              {!! Form::label('body', 'Body') !!}
                              {!! Form::textarea('body', null, ['class' => 'form-control ckeditor']) !!}
                              <small class="text-danger">{{ $errors->first('body') }}</small>
                          </div>

                          <div class="form-group">
                            <div class="g-recaptcha{{ $errors->has('g-recaptcha-response') ? ' has-error' : '' }}" data-sitekey="{{ env('GOOGLE_RECAPTCHA_KEY') }}">
                            </div>
                            @if ($errors->has('g-recaptcha-response'))
                                <span class="help-block"> 
                                    <small class="text-danger">{{ $errors->first('g-recaptcha-response') }}</small>
                                </span>
                            @endif
                          </div> 

                          {!! Form::submit('Create new topic', ['class'=>'btn btn-primary btn-block']) !!}
        
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
  <script src="{{ url('js/ckeditor/ckeditor.js') }}"></script>
  <script src="{{ url('js/ckeditor/config.js') }}"></script>
  
@endsection

resources/views/topics/edit.blade.php
@extends('layouts.app')

@section('style')

@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
          
            <div class="panel panel-default">
                <div class="panel-heading">Create new topic</div>

                <div class="panel-body">
                    {!! Form::model($topic, ['route' => ['topics.update', $topic->slug], 'method' => 'patch'])!!}
                          <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                              {!! Form::label('title', 'Title') !!}
                              {!! Form::text('title', null, ['class' => 'form-control']) !!}
                              <small class="text-danger">{{ $errors->first('title') }}</small>
                          </div>  

                          <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                              {!! Form::label('body', 'Body') !!}
                              {!! Form::textarea('body', null, ['class' => 'form-control ckeditor']) !!}
                              <small class="text-danger">{{ $errors->first('body') }}</small>
                          </div>
                          

                          {!! Form::submit('Update topic', ['class'=>'btn btn-primary btn-block']) !!}
        
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
  <script src="{{ url('js/ckeditor/ckeditor.js') }}"></script>
  <script src="{{ url('js/ckeditor/config.js') }}"></script>
  
@endsection

resources/views/topics/show.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row">
      <div class="col-sm-12">
          

        <a href="{{ route('topics.comments.create', [$topic->slug]) }}" 
           class="btn btn-default pull-left">Comment</a>
           
        <div class="form-group{{ $errors->has('rating') ? ' has-error' : '' }}">
            {!! Form::label('rating', 'Give Rating', ['class' => 'col-sm-3 control-label']) !!}
          <div class="col-sm-9">
            {!! Form::hidden('rating', null, ['class' => 'rating', 'id' => 'rating']) !!}  
          </div>
        </div>

        <span class="pull-right" style="margin-top:-45px;height:70px;">          
          {!! $comments->links() !!}
        </span>
        <br>
        <br>


        {{-- Post page --}}

        @if (!request('page') == 1 or request('page') == 1)
          <div class="panel panel-default change-panel">
            <div class="panel-heading">
              <img src="http://i.kaskus.id/e3.1/images/banner-kasads-new.png" alt="" style="width:90px;height:70px;" class="pull-left img-rounded">  
              <div class="topic-panel">
                
                @if(Auth::check() && Auth::user()->id == $topic->user->id)
                  <a href="{{ route('topics.edit', $topic->slug) }}" class="btn btn-default pull-right" style="padding:3px 10px;">Edit</a>
                @endif
                <h4>&nbsp;&nbsp;{{ $topic->title }}</h4>
                <h5>&nbsp;&nbsp;&nbsp;<a href="#" style="color:#777;" >{{ ucwords($topic->user->name) }}</a></h5>
              </div>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                  {!! $topic->body !!}
                </li>
            </ul>
          </div>
        @endif


        {{-- Comment page --}}

        @foreach ($comments as $comment)
          <div class="panel panel-default change-panel">
            <div class="panel-heading" style="padding-bottom:15px;">
              <img src="http://i.kaskus.id/e3.1/images/banner-kasads-new.png"  style="width:90px;height:70px;" class="pull-left img-rounded">  
              <div class="topic-panel">                
                @if(Auth::check() && Auth::user()->id == $comment->user_id)
                  <a href="{{ route('topics.comments.edit', [$topic->slug, $comment->id, 'page' => $comments->currentPage()]) }}" class="btn btn-default pull-right" style="padding:3px 10px;">Edit Comment</a>
                @endif
                <h5>&nbsp;&nbsp;&nbsp;<a href="#" style="color:#777;" >{{ ucwords($comment->user->name) }}</a></h5>
                <h5>&nbsp;&nbsp;{{ $comment->created_at }}</h5>
              </div>
            </div>

            <ul class="list-group">
                <li class="list-group-item">
                  {!! $comment->body !!}
                </li>
            </ul>
          </div>
        @endforeach
        
        <span class="pull-right">          
          {!! $comments->links() !!}
        </span>
    

      </div>
    </div> {{-- end col-12 --}}
</div>
@endsection

@section('style')
  <link rel="stylesheet" href="{{ url('css/bootstrap-rating.css') }}">
  <style>
    .rating-symbol{
      color: #f6e729;
      height: 20px;
    }
    .glyphicon {
        position: relative;
        top: 1px;
        display: inline-block;
        font-family: 'Glyphicons Halflings';
        font-style: normal;
        font-weight: 400;
        font-size: 21px;
        line-height: 1;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
  </style>
@endsection

@section('script')
  <script src="{{ url('js/bootstrap-rating.js') }}"></script>
  <script>
    $('#rating').rating('rate', {{ $topic->averageRating ? $topic->averageRating : 0 }});
    $('#rating').on('change', function () {
      var token = '{{ csrf_token() }}';

      $.ajax({
          url: '{{ route('topics.star', $topic->slug) }}',
          type:"POST",
          data: { 
            'rating' : this.value,
            '_token' : token
          },
          success: function(result){
              alert(result);
          },
          statusCode: {
            401 : function (){
              alert('You must login first');
            }
          }
      });

    });   
  </script>
@stop