routes/web.php
<?php


/**
 * Home page
 */
Route::get('/', 'HomeController@index');
Route::get('/create_topic', 'HomeController@createTopic')->name('home.create_topic');
Route::post('/create_topic', 'HomeController@storeTopic')->name('home.store_topic');


/**
 * Admin Dashboard
 */
Route::get('/admin', 'Admin\DashboardController@index')->name('admin.dashboard'); 
Route::group([
  'prefix' => 'admin', 
  'namespace' => 'Admin',
  'as' => 'admin.'
], function(){
  
  Route::resource('forums', 'ForumsController',[
    'except' => ['show']
  ]);

  Route::get('categories/pdf', 'CategoriesController@pdf')->name('categories.pdf');
  Route::resource('categories', 'CategoriesController',[
    'except' => ['show']
  ]);
});

/**
 * Forum pages
 */
Route::resource('forums', 'ForumsController',[
  'only' => 'show'
]);
Route::resource('forums.categories', 'CategoriesController', [
  'only' => 'show'
]);


/**
 * Topic And Comment Pages
 */
Route::resource('forums.categories.topics', 'TopicsController',[
  'only' => ['create', 'store']
]);
Route::resource('topics', 'TopicsController', [
  'only' => ['show', 'edit', 'update']
]);
Route::post('/topics/{slug}/postStar', 'TopicsController@postStar')->name('topics.star');
Route::resource('topics.comments', 'CommentsController',[
  'except' => ['index', 'show', 'destroy']
]);



/**
 * Profile pages
 */
Auth::routes();
Route::get('/profile/password', 'ProfileController@editPassword')->name('profile.edit_password');
Route::post('/profile/password', 'ProfileController@updatePassword')->name('profile.update_password');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::patch('/profile/update', 'ProfileController@update')->name('profile.update');

/**
 * Message pages
 */

Route::get('/profile/message', 'MessageController@index')->name('profile.message.index');
Route::resource('profile.message', 'MessageController', [
  'except' => ['index','edit','destroy']
]);
Route::get('/profile/{id}', 'ProfileController@show')->name('profile.show');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'user_id', 'forum_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function forum()
    {
        return $this->belongsTo('App\Forum');
    }

    public function topics()
    {
        return $this->hasMany('App\Topic', 'category_id');
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Forum;
use App\Category;
use Auth;
use PDF;

class CategoriesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','admin']);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $forums = Forum::pluck('name', 'id');
        return view('admin.categories.create', compact('forums'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|unique:categories,name',
          'forum_id' => 'required'
        ]);

        $data            = $request->only(['name', 'forum_id']);
        $data['user_id'] = Auth::user()->id;


        Category::create($data);
        flash('Success create new Category');
        return redirect()->route('admin.categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $forums = Forum::pluck('name', 'id');

        return view('admin.categories.edit', compact('category', 'forums'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
          'name' => 'required',
          'forum_id' => 'required'
        ]);

        $category = Category::findOrFail($id);
        $category->update($request->all());

        flash('Update success');
        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        flash("Success Destroy");
        return redirect()->route('admin.categories.index');
    }

    public function pdf()
    {
        $categories = Category::all();
        $pdf = PDF::loadView('admin.pdf.categories', ['categories' => $categories]);
        return $pdf->stream();
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoriesController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int  $forumId, $categoryId
     * @return \Illuminate\Http\Response
     */
    public function show($forumId, $categoryId)
    {
        $category = Category::findOrFail($categoryId);
        $topics = $category->topics()->orderBy('created_at', 'DESC')->paginate(10);        
        return view('categories.show', compact('category', 'topics', 'forumId', 'categoryId'));
    }

}

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
          <a href="{{ route('forums.categories.topics.create', [$forumId, $categoryId]) }}" class="btn btn-default pull-right">Create new topic</a>
          <br>
          <br>

          <div class="panel panel-default">
            <div class="panel-heading">
              <b>{{ $category->name }}</b><span class="pull-right glyphicon glyphicon-pushpin"></span>
            </div>

            @if (count($topics) == null)
                <div class="panel-body">
                    Have no post 
                </div>
            @endif    

            @foreach($topics as $topic)
                <ul class="list-group">
                  <a href="{{ route('topics.show', $topic->slug) }}" class="list-group-item" style="padding:10px 1px">
                    <div class="col-md-10 col-xs-9">
                      {{ $topic->title }} <br>
                      @if (count($topic->ratings))
                        @for ($i = 0; $i < $topic->averageRating ; $i++)
                          <i class="glyphicon glyphicon-star" style="color:#f6e729;"></i>
                        @endfor
                      @endif
                    </div>
                    <p style="font-size:12px;margin-top:2px;" class="">
                      <span class="fa fa-comments"></span> : {{ count($topic->comments) }} Replies <br>
                      <span class="glyphicon glyphicon-eye-open"></span> : {{ $topic->views }} Views
                    </p>
                  </a>
                </ul>
            @endforeach
          </div>
          <span class="pull-right">{!! $topics->links() !!}</span>
        </div>
    </div>
</div>
@endsection