routes/web.php
<?php


/**
 * Home page
 */
Route::get('/', 'HomeController@index');
Route::get('/create_topic', 'HomeController@createTopic')->name('home.create_topic');
Route::post('/create_topic', 'HomeController@storeTopic')->name('home.store_topic');


/**
 * Admin Dashboard
 */
Route::get('/admin', 'Admin\DashboardController@index')->name('admin.dashboard'); 
Route::group([
  'prefix' => 'admin', 
  'namespace' => 'Admin',
  'as' => 'admin.'
], function(){
  
  Route::resource('forums', 'ForumsController',[
    'except' => ['show']
  ]);

  Route::get('categories/pdf', 'CategoriesController@pdf')->name('categories.pdf');
  Route::resource('categories', 'CategoriesController',[
    'except' => ['show']
  ]);
});

/**
 * Forum pages
 */
Route::resource('forums', 'ForumsController',[
  'only' => 'show'
]);
Route::resource('forums.categories', 'CategoriesController', [
  'only' => 'show'
]);


/**
 * Topic And Comment Pages
 */
Route::resource('forums.categories.topics', 'TopicsController',[
  'only' => ['create', 'store']
]);
Route::resource('topics', 'TopicsController', [
  'only' => ['show', 'edit', 'update']
]);
Route::post('/topics/{slug}/postStar', 'TopicsController@postStar')->name('topics.star');
Route::resource('topics.comments', 'CommentsController',[
  'except' => ['index', 'show', 'destroy']
]);



/**
 * Profile pages
 */
Auth::routes();
Route::get('/profile/password', 'ProfileController@editPassword')->name('profile.edit_password');
Route::post('/profile/password', 'ProfileController@updatePassword')->name('profile.update_password');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::patch('/profile/update', 'ProfileController@update')->name('profile.update');

/**
 * Message pages
 */

Route::get('/profile/message', 'MessageController@index')->name('profile.message.index');
Route::resource('profile.message', 'MessageController', [
  'except' => ['index','edit','destroy']
]);
Route::get('/profile/{id}', 'ProfileController@show')->name('profile.show');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'user_id', 'forum_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function forum()
    {
        return $this->belongsTo('App\Forum');
    }

    public function topics()
    {
        return $this->hasMany('App\Topic', 'category_id');
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Forum;
use App\Category;
use Auth;
use PDF;

class CategoriesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth','admin']);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $forums = Forum::pluck('name', 'id');
        return view('admin.categories.create', compact('forums'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|unique:categories,name',
          'forum_id' => 'required'
        ]);

        $data            = $request->only(['name', 'forum_id']);
        $data['user_id'] = Auth::user()->id;


        Category::create($data);
        flash('Success create new Category');
        return redirect()->route('admin.categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $forums = Forum::pluck('name', 'id');

        return view('admin.categories.edit', compact('category', 'forums'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
          'name' => 'required',
          'forum_id' => 'required'
        ]);

        $category = Category::findOrFail($id);
        $category->update($request->all());

        flash('Update success');
        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        flash("Success Destroy");
        return redirect()->route('admin.categories.index');
    }

    public function pdf()
    {
        $categories = Category::all();
        $pdf = PDF::loadView('admin.pdf.categories', ['categories' => $categories]);
        return $pdf->stream();
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoriesController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int  $forumId, $categoryId
     * @return \Illuminate\Http\Response
     */
    public function show($forumId, $categoryId)
    {
        $category = Category::findOrFail($categoryId);
        $topics = $category->topics()->orderBy('created_at', 'DESC')->paginate(10);        
        return view('categories.show', compact('category', 'topics', 'forumId', 'categoryId'));
    }

}

resources/views/admin/categories/_form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
    <small class="text-danger">{{ $errors->first('name') }}</small>
</div>

<div class="form-group{{ $errors->has('forums') ? ' has-error' : '' }}">
    {!! Form::label('forums', 'Forums') !!}
    {!! Form::select('forum_id',$forums, isset($model) ? $model->forum_id : '' , ['id' => 'forums', 'class' => 'form-control', 'required' => 'required']) !!}
    <small class="text-danger">{{ $errors->first('forums') }}</small>
</div>

{!! Form::submit(isset($model) ? 'Update' : 'Save', ['class'=>'btn btn-primary']) !!}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create new category</div>

                <div class="panel-body">
                    {!! Form::open(['route' => 'admin.categories.store'])!!}
                          @include('admin.categories._form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body"> 
                  {!! Form::model($category, ['route' => ['admin.categories.update', $category], 'method' => 'patch'])!!}
                        @include('admin.categories._form', ['model' => $category])
                  {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')


@section('content')


<div class="container">
    <div class="row">
        @include('admin.partials._list')

        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">Categories 
                  <a href="{{ route('admin.categories.create') }}" class="btn btn-default btn-xs pull-right">Create new Category</a> 
                  <a href="{{ route('admin.categories.pdf') }}" class="btn btn-default btn-xs pull-right">Export To Pdf</a>
                </div>

                <div class="panel-body">
                  @if (count($categories) == null)
                     Have no category
                  @else
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Forum</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($categories as $category)
                          <tr>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->forum->name }}</td>
                            <td>
                              {!! Form::model($category, ['route' => ['admin.categories.destroy', $category], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                               <a href="{{ route('admin.categories.edit', $category->id)}}" class="btn btn-sm btn-info">Edit</a> |
                                {!! Form::submit('Delete', ['class'=>'btn btn-sm btn-danger']) !!}
                              {!! Form::close()!!}
                            </td>
                          </tr>
                        @endforeach
                      </tbody>
                    </table>
                  @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection